backend:
  name: github
  repo: anderslura/hjelpeportalen-nettside
  branch: main

  # Netlify OAuth (bruker OAUTH_CLIENT_ID / OAUTH_CLIENT_SECRET du la inn)
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_id: extraordinary-dasik-edfc62   # <- VIKTIG: uten ".netlify.app"

site_url: "https://hjelpeportalen.no"
display_url: "https://hjelpeportalen.no"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Sider"
    files:
      - file: "content/home.md"
        name: "home"
        label: "Forside"
        fields:
          - { label: "Tittel", name: "title", widget: "string" }
          - { label: "Ingress", name: "lead", widget: "text", required: false }
          - { label: "Innhold", name: "body", widget: "markdown" }
