backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "content/uploads"
public_folder: "/content/uploads"

site_url: https://hjelpeportalen.no
display_url: https://hjelpeportalen.no

collections:
  - name: "pages"
    label: "Sider"
    files:
      - file: "content/home.md"
        label: "Forside"
        name: "home"
        fields:
          - { label: "Tittel", name: "title", widget: "string" }
          - { label: "Ingress", name: "intro", widget: "text" }
          - { label: "Innhold", name: "body", widget: "markdown" }
