backend:
  name: github
  repo: anderslura/hjelpeportalen-nettside
  branch: main
  site_id: d4e68a46-ea32-4653-b7c2-822254a93227

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Sider"
    files:
      - name: "home"
        label: "Forside"
        file: "content/home.md"
        fields:
          - { label: "Tittel", name: "title", widget: "string" }
          - { label: "Innhold", name: "body", widget: "markdown" }
