backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

locale: "nb"

collections:
  - name: "pages"
    label: "Sider"
    files:
      - name: "home"
        label: "Forside"
        file: "content/home.json"
        format: "json"
        fields:
          - { label: "Tittel", name: "title", widget: "string" }
          - { label: "Ingress", name: "ingress", widget: "string" }
          - { label: "Innhold", name: "body", widget: "markdown" }
