backend:
  name: github
  repo: anderslura/hjelpeportalen-nettside
  branch: main

site_url: "https://hjelpeportalen.no"
display_url: "https://hjelpeportalen.no"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Sider"
    files:
      - file: "content/home.md"
        name: "home"
        label: "Forside"
        fields:
          - { label: "Tittel", name: "title", widget: "string" }
          - { label: "Ingress", name: "lead", widget: "text", required: false }
          - { label: "Innhold", name: "body", widget: "markdown" }
